"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { ArrowUpRight,Check,RefreshCw,Search,SlidersHorizontal,X,Zap } from "lucide-react";
import { rupees,API,KEY } from "@/lib/api";
import { EmptyState,LoadingState,OperationsHeader,SegmentedFilter,StatTile } from "@/components/OperationsUI";
import { StatusBadge } from "@/components/StatusBadge";

export default function PaymentsPage(){
  const [payments,setPayments]=useState<any[]>([]),[filter,setFilter]=useState<"all"|"failed"|"captured">("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[recoveringId,setRecoveringId]=useState<string|null>(null),[results,setResults]=useState<Record<string,any>>({}),[notice,setNotice]=useState<string|null>(null);
  async function load(){try{setLoading(true);const res=await fetch(`${API}/api/payments`,{headers:{"X-API-Key":KEY}});if(!res.ok)throw new Error("Failed to fetch payments");setPayments(await res.json())}catch(e:any){setNotice(`Could not load payments: ${e.message}`)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function recover(id:string){try{setRecoveringId(id);const res=await fetch(`${API}/api/recovery/${id}/run`,{method:"POST",headers:{"Content-Type":"application/json","X-API-Key":KEY}});if(!res.ok)throw new Error(await res.text()||"Recovery failed");const data=await res.json();setResults(p=>({...p,[id]:data}));setNotice(`Recovery case #${data.id} started successfully.`)}catch(e:any){setNotice(`Recovery failed: ${e.message}`)}finally{setRecoveringId(null)}}
  async function recoverAll(){try{setLoading(true);const res=await fetch(`${API}/api/recovery/batch-run`,{method:"POST",headers:{"Content-Type":"application/json","X-API-Key":KEY}});if(!res.ok)throw new Error(await res.text());const data=await res.json();setNotice(`${data.total_processed} failures moved into the recovery workflow.`);await load()}catch(e:any){setNotice(`Batch recovery failed: ${e.message}`)}finally{setLoading(false)}}
  const failed=payments.filter(p=>p.status==="failed"),failedValue=failed.reduce((n,p)=>n+(p.amount_paise||0),0);
  const visible=useMemo(()=>payments.filter(p=>(filter==="all"||p.status===filter)&&(!query||`${p.payment_id} ${p.customer_id} ${p.failure_reason}`.toLowerCase().includes(query.toLowerCase()))),[payments,filter,query]);
  return <>
    <OperationsHeader eyebrow="Payment telemetry" title="Payments" description="Monitor transaction health, isolate revenue leakage, and move eligible failures into bounded recovery." actions={<><button onClick={load} className="flex h-9 items-center gap-2 rounded-lg border border-white/[.08] bg-white/[.025] px-3 text-[10px] font-medium text-zinc-400 hover:text-zinc-200"><RefreshCw size={13}/> Refresh</button><button onClick={recoverAll} disabled={loading||!failed.length} className="flex h-9 items-center gap-2 rounded-lg bg-emerald-400 px-3.5 text-[10px] font-semibold text-emerald-950 disabled:opacity-40"><Zap size={13}/> Recover failures <span className="rounded bg-emerald-950/10 px-1.5">{failed.length}</span></button></>}/>
    {notice&&<div className="mb-5 flex items-center gap-3 rounded-xl border border-emerald-400/10 bg-emerald-400/[.045] px-4 py-3 text-[10px] text-emerald-200"><Check size={13} className="text-emerald-400"/><span className="flex-1">{notice}</span><button onClick={()=>setNotice(null)}><X size={13}/></button></div>}
    <div className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatTile label="Total transactions" value={payments.length} detail="Across all payment rails"/><StatTile label="Failed transactions" value={failed.length} detail="Eligible for diagnosis" tone="danger"/><StatTile label="Revenue at risk" value={rupees(failedValue)} detail="Open failed payment value" tone="warning"/><StatTile label="Failure rate" value={payments.length?`${(failed.length/payments.length*100).toFixed(1)}%`:"0%"} detail="Current transaction set" tone="neutral"/></div>
    <div className="card overflow-hidden p-0"><div className="flex flex-col gap-3 border-b border-white/[.06] p-4 md:flex-row md:items-center md:justify-between"><SegmentedFilter value={filter} onChange={setFilter} items={[{id:"all",label:"All",count:payments.length},{id:"failed",label:"Failed",count:failed.length},{id:"captured",label:"Captured",count:payments.length-failed.length}]}/><div className="flex items-center gap-2"><label className="flex h-9 min-w-[230px] items-center gap-2 rounded-lg border border-white/[.07] bg-black/20 px-3 text-zinc-600"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search payments or customers" className="w-full bg-transparent text-[10px] text-zinc-300 outline-none placeholder:text-zinc-700"/></label><button className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.07] text-zinc-600"><SlidersHorizontal size={13}/></button></div></div>
      <div className="overflow-x-auto">{loading?<LoadingState label="Loading payment telemetry"/>:visible.length===0?<EmptyState title="No matching payments" detail="Try changing the status filter or search query."/>:<table><thead><tr><th>Payment</th><th>Customer</th><th>Amount</th><th>Rail</th><th>Status</th><th>Failure signal</th><th className="text-right">Next action</th></tr></thead><tbody>{visible.map(r=>{const recovery=results[r.payment_id];return <tr key={r.id}><td><div className="font-mono text-[10px] font-medium text-zinc-300">{r.payment_id}</div><div className="mt-1 text-[9px] text-zinc-700">Transaction event</div></td><td><Link href={`/customers/${r.customer_id}`} className="text-[10px] font-medium text-zinc-400 hover:text-emerald-400">{r.customer_id}</Link></td><td className="text-[11px] font-semibold text-zinc-200">{rupees(r.amount_paise)}</td><td><span className="badge bg-white/[.025] text-[9px] uppercase tracking-wider text-zinc-500">{r.payment_method}</span></td><td><StatusBadge status={r.status}/></td><td><span className={`text-[10px] ${r.failure_reason?"text-amber-300/80":"text-zinc-700"}`}>{r.failure_reason?.replaceAll("_"," ")||"No failure"}</span></td><td><div className="flex justify-end">{r.status==="failed"?(recovery?<Link href="/recovery" className="flex items-center gap-1 text-[10px] font-medium text-emerald-400">Case #{recovery.id} <ArrowUpRight size={11}/></Link>:<button onClick={()=>recover(r.payment_id)} disabled={recoveringId===r.payment_id} className="flex h-7 items-center gap-1.5 rounded-lg border border-emerald-400/20 bg-emerald-400/[.07] px-2.5 text-[9px] font-semibold text-emerald-300 hover:bg-emerald-400/[.12] disabled:opacity-40"><Zap size={11}/>{recoveringId===r.payment_id?"Starting…":"Start recovery"}</button>):<span className="flex items-center gap-1 text-[9px] text-zinc-600"><Check size={11} className="text-emerald-500"/> Settled</span>}</div></td></tr>})}</tbody></table>}</div>
    </div>
  </>;
}
