"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowUpRight,Calculator,CheckCircle2,RefreshCw,Sparkles,Target } from "lucide-react";
import { rupees,API,KEY } from "@/lib/api";
import { EmptyState,LoadingState,OperationsHeader,StatTile } from "@/components/OperationsUI";

export default function OpportunitiesPage(){
  const [items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true),[budget,setBudget]=useState(2500),[optimizing,setOptimizing]=useState(false),[result,setResult]=useState<any>(null);
  async function load(){try{setLoading(true);const res=await fetch(`${API}/api/opportunities`,{headers:{"X-API-Key":KEY}});if(!res.ok)throw new Error("Failed to load opportunities");setItems(await res.json())}catch(e){console.error(e)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function optimize(){try{setOptimizing(true);const res=await fetch(`${API}/api/opportunities/optimize-budget`,{method:"POST",headers:{"Content-Type":"application/json","X-API-Key":KEY},body:JSON.stringify({budget_paise:budget*100})});if(!res.ok)throw new Error("Budget optimization failed");setResult(await res.json())}catch(e){console.error(e)}finally{setOptimizing(false)}}
  const atRisk=items.reduce((n,o)=>n+(o.amount_paise||0),0),expected=items.reduce((n,o)=>n+(o.expected_net_recovery_paise||0),0),probability=items.length?items.reduce((n,o)=>n+(o.recovery_probability||0),0)/items.length*100:0;
  return <>
    <OperationsHeader eyebrow="Prioritization" title="Recovery opportunities" description="Rank payment, checkout, and subscription failures by expected net value—then allocate intervention budget to the strongest returns." actions={<button onClick={load} className="flex h-9 items-center gap-2 rounded-lg border border-white/[.08] bg-white/[.025] px-3 text-[10px] font-medium text-zinc-400"><RefreshCw size={13}/> Refresh data</button>}/>
    <div className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatTile label="Open opportunities" value={items.length} detail="Ranked across all sources"/><StatTile label="Revenue at risk" value={rupees(atRisk)} detail="Total available recovery value" tone="warning"/><StatTile label="Expected net recovery" value={rupees(expected)} detail="Probability and cost adjusted" tone="positive"/><StatTile label="Average probability" value={`${probability.toFixed(0)}%`} detail="Model confidence across queue" tone="neutral"/></div>
    <div className="card mb-6 overflow-hidden p-0"><div className="grid lg:grid-cols-[1fr_auto]"><div className="border-b border-white/[.06] p-5 lg:border-b-0 lg:border-r"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-emerald-400/10 bg-emerald-400/[.06] text-emerald-400"><Calculator size={16}/></span><div><h2 className="text-[13px] font-semibold text-zinc-200">Recovery budget optimizer</h2><p className="mt-1 max-w-xl text-[10px] leading-5 text-zinc-600">Select the highest expected-return interventions while remaining inside your cost ceiling.</p></div></div><div className="mt-5 flex flex-wrap items-center gap-2">{[1000,2500,5000,10000].map(v=><button key={v} onClick={()=>setBudget(v)} className={`rounded-lg border px-3 py-1.5 text-[9px] font-medium ${budget===v?"border-emerald-400/20 bg-emerald-400/[.08] text-emerald-300":"border-white/[.06] text-zinc-600 hover:text-zinc-300"}`}>₹{v.toLocaleString("en-IN")}</button>)}</div></div><div className="flex min-w-[300px] flex-col justify-center p-5"><label className="text-[9px] font-medium uppercase tracking-[.12em] text-zinc-600">Custom budget</label><div className="mt-2 flex items-center gap-2"><div className="flex h-10 flex-1 items-center rounded-lg border border-white/[.07] bg-black/20 px-3 text-[11px] text-zinc-500">₹<input type="number" min="100" step="500" value={budget} onChange={e=>setBudget(Number(e.target.value))} className="ml-1 w-full bg-transparent font-semibold text-zinc-200 outline-none"/></div><button onClick={optimize} disabled={optimizing} className="flex h-10 items-center gap-2 rounded-lg bg-emerald-400 px-4 text-[10px] font-semibold text-emerald-950 disabled:opacity-50"><Sparkles size={13}/>{optimizing?"Optimizing…":"Optimize"}</button></div></div></div>
      {result&&<div className="grid grid-cols-2 gap-px border-t border-white/[.06] bg-white/[.05] md:grid-cols-4">{[{l:"Selected",v:`${result.selected?.length||0} / ${items.length}`},{l:"Intervention cost",v:rupees(result.total_cost_paise||0)},{l:"Expected recovery",v:rupees(result.total_expected_net_recovery_paise||0)},{l:"Projected ROI",v:result.total_cost_paise?`${(result.total_expected_net_recovery_paise/result.total_cost_paise*100).toFixed(0)}%`:"—"}].map(x=><div key={x.l} className="bg-[#101412] p-4"><div className="text-[9px] text-zinc-600">{x.l}</div><div className="mt-1 text-[14px] font-semibold text-zinc-200">{x.v}</div></div>)}</div>}
    </div>
    <div className="card overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white/[.06] px-5 py-4"><div><h2 className="text-[13px] font-semibold text-zinc-200">Ranked opportunity queue</h2><p className="mt-1 text-[10px] text-zinc-600">Ordered by probability-adjusted net recovery</p></div><span className="text-[9px] text-zinc-600">{items.length} records</span></div><div className="overflow-x-auto">{loading?<LoadingState label="Scoring recovery opportunities"/>:items.length===0?<EmptyState title="No opportunities found" detail="New failed payment, checkout, and subscription events will appear here."/>:<table><thead><tr><th>Rank & source</th><th>Customer</th><th>Revenue at risk</th><th>Probability</th><th>Cost</th><th>Expected net</th><th>Recommendation</th></tr></thead><tbody>{items.map((r,i)=>{const selected=result?.selected?.some((s:any)=>s.source_id===r.source_id);const pct=(r.recovery_probability||0)*100;return <tr key={`${r.source_type}-${r.source_id}-${i}`} className={selected?"bg-emerald-400/[.025]":""}><td><div className="flex items-center gap-3"><span className="w-5 text-[9px] font-medium text-zinc-700">{String(i+1).padStart(2,"0")}</span><span className={`grid h-8 w-8 place-items-center rounded-lg ${r.source_type==="payment"?"bg-sky-400/[.07] text-sky-400":r.source_type==="checkout"?"bg-amber-400/[.07] text-amber-400":"bg-violet-400/[.07] text-violet-400"}`}><Target size={13}/></span><div><div className="text-[10px] font-medium capitalize text-zinc-300">{r.source_type}</div><div className="mt-0.5 font-mono text-[8px] text-zinc-700">{r.source_id}</div></div></div></td><td><Link href={`/customers/${r.customer_id}`} className="text-[10px] text-zinc-400 hover:text-emerald-400">{r.customer_id}</Link></td><td className="text-[11px] font-semibold text-zinc-200">{rupees(r.amount_paise)}</td><td><div className="w-24"><div className="mb-1 flex justify-between text-[9px]"><span className="text-zinc-500">Confidence</span><span className="font-medium text-zinc-300">{pct.toFixed(0)}%</span></div><div className="h-1 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-emerald-400" style={{width:`${pct}%`}}/></div></div></td><td className="text-[10px] text-zinc-500">{rupees(r.intervention_cost_paise||0)}</td><td className="text-[11px] font-semibold text-emerald-400">{rupees(r.expected_net_recovery_paise)}</td><td><div className="flex items-center justify-between gap-4"><span className="max-w-[170px] truncate text-[9px] capitalize text-zinc-400">{r.recommended_action?.replaceAll("_"," ")}</span>{selected?<span className="flex items-center gap-1 whitespace-nowrap rounded-full border border-emerald-400/10 bg-emerald-400/[.06] px-2 py-1 text-[8px] font-semibold text-emerald-400"><CheckCircle2 size={9}/> Selected</span>:<ArrowUpRight size={12} className="text-zinc-700"/>}</div></td></tr>})}</tbody></table>}</div></div>
  </>;
}
