"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft,CheckCircle2,Clock3,CreditCard,ExternalLink,FileText,Pause,Play,RefreshCw,Send,ShieldCheck,Square,UserRound } from "lucide-react";
import { api,rupees } from "@/lib/api";
import type { RecoveryCaseDetail } from "@/lib/types";
import { LoadingState } from "@/components/OperationsUI";
import { StatusBadge } from "@/components/StatusBadge";

export default function CaseWorkspace(){
 const params=useParams(),id=Number(params.id);const [data,setData]=useState<RecoveryCaseDetail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[note,setNote]=useState(""),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setError(null);setData(await api<RecoveryCaseDetail>(`/api/recovery/cases/${id}`))}catch(e:any){setError(e.message)}finally{setLoading(false)}},[id]); useEffect(()=>{load()},[load]);
 async function command(action:string){try{setBusy(true);setError(null);await api(`/api/recovery/cases/${id}/command`,{method:"POST",body:JSON.stringify({action,note:note||undefined})});setNote("");await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <LoadingState label="Loading recovery workspace"/>; if(!data)return <div className="card text-sm text-rose-300">{error||"Case not found"}</div>; const c=data.case; const canPause=["created","approved","executing"].includes(c.status),canResume=c.status==="paused",canStop=["created","approved","executing","paused","waiting_human_review"].includes(c.status),canRetry=["stopped","failed"].includes(c.status);
 return <>
  <div className="mb-6 flex items-center justify-between border-b border-white/[.06] pb-5"><Link href="/recovery" className="flex items-center gap-2 text-[10px] text-zinc-500 hover:text-zinc-200"><ArrowLeft size={13}/> Recovery cases</Link><button onClick={load} className="flex items-center gap-2 text-[10px] text-zinc-600"><RefreshCw size={12}/> Refresh</button></div>
  <section className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.14em] text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/> Case workspace</div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-[-.04em]">Recovery case #{c.id}</h1><StatusBadge status={c.status}/></div><p className="mt-2 text-[11px] text-zinc-600">Created {new Date(c.created_at).toLocaleString("en-IN")} · {c.source_type} · {c.payment_id}</p></div><div className="flex flex-wrap gap-2">{canPause&&<Action onClick={()=>command("pause")} icon={<Pause size={12}/>} label="Pause"/>}{canResume&&<Action onClick={()=>command("resume")} icon={<Play size={12}/>} label="Resume"/>}{canRetry&&<Action onClick={()=>command("retry")} icon={<RefreshCw size={12}/>} label="Retry"/>}{canStop&&<Action onClick={()=>command("stop")} icon={<Square size={11}/>} label="Stop" danger/>}{c.external_url&&<a href={c.external_url} target="_blank" rel="noreferrer" className="flex h-9 items-center gap-2 rounded-lg bg-emerald-400 px-3 text-[10px] font-semibold text-emerald-950">Open payment link <ExternalLink size={11}/></a>}</div></section>
  {error&&<div className="mb-5 rounded-xl border border-rose-400/10 bg-rose-400/[.05] px-4 py-3 text-[10px] text-rose-300">{error}</div>}
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.55fr)]"><div className="space-y-4"><div className="card p-0"><Section title="Recovery decision" subtitle="Model output, economics, and bounded action" icon={<ShieldCheck size={14}/>}/><div className="grid grid-cols-2 gap-px bg-white/[.05] md:grid-cols-4">{[{l:"Amount",v:rupees(c.amount_paise)},{l:"Recovery probability",v:`${((c.recovery_probability||0)*100).toFixed(0)}%`},{l:"Expected net",v:rupees(c.expected_net_recovery_paise)},{l:"Intervention cost",v:rupees(c.intervention_cost_paise)}].map(x=><div key={x.l} className="bg-[#101412] p-4"><div className="text-[9px] text-zinc-600">{x.l}</div><div className="mt-1 text-[14px] font-semibold text-zinc-200">{x.v}</div></div>)}</div><div className="grid gap-4 border-t border-white/[.06] p-5 md:grid-cols-2"><Info label="Diagnosis" value={c.diagnosis?.replaceAll("_"," ")||"Not available"}/><Info label="Selected action" value={c.selected_action?.replaceAll("_"," ")||"Not selected"}/><Info label="Policy decision" value={c.policy_status||"Not evaluated"}/><Info label="Policy reason" value={c.policy_reason||"No policy explanation"}/></div></div>
   <div className="card p-0"><Section title="Execution timeline" subtitle="Immutable decisions and operational events" icon={<Clock3 size={14}/>}/><div className="p-5">{data.events.length?data.events.map((e,i)=><div key={e.id} className="relative flex gap-4 pb-6 last:pb-0"><div className="relative z-10 mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border border-emerald-400/10 bg-emerald-400/[.06] text-emerald-400"><CheckCircle2 size={11}/></div>{i<data.events.length-1&&<span className="absolute bottom-0 left-[13px] top-7 w-px bg-white/[.06]"/>}<div><div className="text-[10px] font-medium capitalize text-zinc-300">{e.event_type.replaceAll("_"," ")}</div><p className="mt-1 text-[10px] leading-5 text-zinc-600">{e.message}</p><time className="mt-1 block text-[8px] text-zinc-700">{new Date(e.created_at).toLocaleString("en-IN")}</time></div></div>):<div className="py-8 text-center text-[10px] text-zinc-600">No recorded case events</div>}</div></div>
  </div><aside className="space-y-4"><div className="card p-0"><Section title="Customer & payment" subtitle="Context for this recovery" icon={<UserRound size={14}/>}/><div className="space-y-4 p-5"><Info label="Customer" value={c.customer_id}/><Info label="Payment rail" value={data.payment?.payment_method||"Unknown"}/><Info label="Bank" value={data.payment?.bank||"Not provided"}/><Info label="Failure reason" value={data.payment?.failure_reason?.replaceAll("_"," ")||"Not provided"}/><Link href={`/customers/${c.customer_id}`} className="flex items-center gap-1 text-[10px] font-medium text-emerald-400">Open customer history <ExternalLink size={10}/></Link></div></div>
   <div className="card p-0"><Section title="Internal note" subtitle="Add context to the audit trail" icon={<FileText size={14}/>}/><div className="p-5"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Add investigation notes or handoff context…" className="w-full resize-none rounded-xl border border-white/[.07] bg-black/20 p-3 text-[10px] leading-5 text-zinc-300 outline-none placeholder:text-zinc-700 focus:border-emerald-400/20"/><button onClick={()=>command("note")} disabled={busy||!note.trim()} className="mt-2 flex h-8 w-full items-center justify-center gap-2 rounded-lg bg-white/[.06] text-[9px] font-semibold text-zinc-300 disabled:opacity-40"><Send size={11}/> Add note</button></div></div>
   <div className="card p-0"><Section title="Recovery actions" subtitle={`${data.actions.length} action${data.actions.length===1?"":"s"} recorded`} icon={<CreditCard size={14}/>}/><div className="divide-y divide-white/[.05]">{data.actions.map(a=><div key={a.id} className="p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-medium capitalize text-zinc-300">{a.action_type.replaceAll("_"," ")}</span><StatusBadge status={a.status}/></div><div className="mt-1 text-[8px] text-zinc-700">{a.provider} · {a.execution_mode}</div></div>)}{!data.actions.length&&<div className="p-5 text-[10px] text-zinc-600">No action executed yet.</div>}</div></div>
  </aside></div>
 </>;
}
function Section({title,subtitle,icon}:{title:string;subtitle:string;icon:React.ReactNode}){return <div className="flex items-center gap-3 border-b border-white/[.06] px-5 py-4"><span className="text-emerald-400">{icon}</span><div><h2 className="text-[12px] font-semibold text-zinc-200">{title}</h2><p className="mt-0.5 text-[9px] text-zinc-600">{subtitle}</p></div></div>}
function Info({label,value}:{label:string;value:string}){return <div><div className="text-[8px] font-medium uppercase tracking-[.12em] text-zinc-700">{label}</div><div className="mt-1 text-[10px] capitalize text-zinc-300">{value}</div></div>}
function Action({onClick,icon,label,danger=false}:{onClick:()=>void;icon:React.ReactNode;label:string;danger?:boolean}){return <button onClick={onClick} className={`flex h-9 items-center gap-2 rounded-lg border px-3 text-[10px] font-medium ${danger?"border-rose-400/10 bg-rose-400/[.04] text-rose-300":"border-white/[.08] bg-white/[.025] text-zinc-400"}`}>{icon}{label}</button>}
